In [2]:
import numpy as np

my_lst=[1,2,3,4,5]
arr=np.array(my_lst) 
type(arr)

numpy.ndarray

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
arr.shape

(5,)

In [7]:
# arr.reshape(5,1)
arr

array([1, 2, 3, 4, 5])

In [14]:
my_lst1=[1,2,3,4,5]
my_lst2=[1,2,3,4,5]
my_lst3=[1,2,3,4,5]

arr=np.array([my_lst1,my_lst2,my_lst3])
arr
arr.reshape(5,3)
arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [15]:
arr.reshape(5,3) #5 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 1],
       [2, 3, 4],
       [5, 1, 2],
       [3, 4, 5]])

In [32]:
#indexing 

arr[0][1]
arr[:3]
arr[0:1]
arr[0:2,0:2]
arr[1:2,1:2]
arr[1:3,3:5] #basically row -1 and 2 and in that columns 3 and 4 
arr[1:2,2:3]


array([[3]])

In [37]:
arr=np.arange(0,10)
arr=arr.reshape(2,5)
arr
np.linspace(1,10,50) # start and stop value and number of values between them

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [38]:
arr1=arr.copy()#this will make it so that makign changes in arr1 wont make changes in arr as it will create a diff space for arr1 instead of just referencing it 
val=2
arr*val

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [39]:
np.ones(4,dtype=float)#creates an array woth float value with all values as 1

array([1., 1., 1., 1.])

In [40]:
#random distribution

np.random.rand(3,3)

array([[0.6610365 , 0.75739912, 0.98376695],
       [0.02413896, 0.70464468, 0.85368204],
       [0.87200462, 0.13505089, 0.88182269]])

In [42]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[-0.38639407,  0.64961013, -0.22834643,  1.19246973],
       [ 0.87767176, -0.20721028,  1.18575468,  0.37224795],
       [ 0.84881419,  0.3929854 ,  0.2371814 , -1.05854088],
       [-1.19238026,  0.27921159,  0.56747932,  0.65857175]])

In [43]:
#array of 10 zeroes
np.zeros(10,dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
arr=np.ones(10,dtype=float)
arr*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [46]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [48]:
arr=np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [50]:
arr=np.arange(0,9)
arr=arr.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
np.identity(3,dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
arr=np.random.rand(1)
arr

array([0.46421703])

In [68]:
arr=np.random.randn(5,5)#uses standard normal distribution
arr

array([[-0.0273926 , -0.88489331, -0.96494689,  1.49346188, -0.01729759],
       [ 0.24359266,  0.0979199 , -1.52947607,  1.96061043,  1.18032858],
       [-0.42517997, -0.58029494, -0.66309931, -0.0341978 , -0.61770598],
       [ 1.42213199, -0.42604375, -0.12209197, -2.04188996, -1.79503037],
       [ 0.90889862,  0.04381312,  0.10349455, -2.53763023, -0.06072984]])

In [80]:
arr=np.linspace(0.00,1.00,100,dtype=float)
arr=arr.reshape(10,10)

arr

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [82]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [83]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [84]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [85]:
mat[3:4,4]

array([20])

In [87]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [88]:
mat[4]

array([21, 22, 23, 24, 25])

In [90]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [91]:
mat.sum()

325

In [94]:
mat.std() #standard deviation

7.211102550927978

In [98]:
array = mat.sum(axis=0) #summ along column
array

array([55, 60, 65, 70, 75])

In [101]:
import pandas as pd
 
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=["row1","row2","row3","row4","row5"],columns=("column1","column2","column3","column4"))

In [102]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [103]:
df.to_csv("test1.csv")

In [104]:
#accessing the elements
## 1 .loc  2 .iloc

df.loc['row1']

column1    0
column2    1
column3    2
column4    3
Name: row1, dtype: int32

In [105]:
type(df.loc['row1'])

pandas.core.series.Series

In [106]:
df.iloc[:,:]# row and column indexes similar to the numpy nd array indexing

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [109]:
#conver to arrays
df.iloc[:,1:].values.shape

(5, 3)

In [110]:
#chck null values
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [112]:
df["column2"].unique()

array([ 1,  5,  9, 13, 17])

In [115]:
df1=pd.read_csv("mercedesbenz.csv")
#u can mention a sep=";..." as a paramter if some other sep. is used
df1.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [117]:
df1.describe()

ID            y          X10     X11          X12  \
count  4209.000000  4209.000000  4209.000000  4209.0  4209.000000   
mean   4205.960798   100.669318     0.013305     0.0     0.075077   
std    2437.608688    12.679381     0.114590     0.0     0.263547   
min       0.000000    72.110000     0.000000     0.0     0.000000   
25%    2095.000000    90.820000     0.000000     0.0     0.000000   
50%    4220.000000    99.150000     0.000000     0.0     0.000000   
75%    6314.000000   109.010000     0.000000     0.0     0.000000   
max    8417.000000   265.320000     1.000000     0.0     1.000000   

               X13          X14          X15          X16          X17  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.057971     0.428130     0.000475     0.002613     0.007603  ...   
std       0.233716     0.494867     0.021796     0.051061     0.086872  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     1.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.318841     0.057258     0.314802     0.020670     0.009503   
std       0.466082     0.232363     0.464492     0.142294     0.097033   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.007603     0.001663     0.000475     0.001426  
std       0.089524     0.086872     0.040752     0.021796     0.037734  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 370 columns]

In [118]:
#unique category counts 
df1['X0'].value_counts()

z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: X0, dtype: int64

In [121]:
from io import StringIO

data =('col1,col2,col3\n'
       'x,y,1\n'
       'a,b,2\n'
       'c,d,3')
df1=pd.read_csv(StringIO(data),usecols=['col1','col2'])
df1

col1 col2
0    x    y
1    a    b
2    c    d